### ISSUE TITLE
Expose ATECC608A vault to Elixir

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#414] opened 2020-09-10 06:17 UTC

**Comment by mrinalwadhwa** [comment] 2020-09-10 06:22
@SanjoDeundiak the goal is to make it possible to replace these functions with Rust equivalents
https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/lib/ockam/channel/xx.ex#L116-L212

**Comment by mrinalwadhwa** [comment] 2020-09-10 06:27
There is a possibility that a call like encode_message_2 is too long to be a NIF ... the concurrency strengths of Erlang VM come from being able to easily schedule thousands of concurrent processes. A long running NIF can totally kill that .... so we;ll have to measure once we have the above in place.

If this works, that would be win because then we won't have to maintain an elixir version of the key exchange.

**Comment by SanjoDeundiak** [comment] 2021-09-09 13:41
Duplicate of #675

**Closed by SanjoDeundiak** 2021-09-09 13:41 UTC
Labels: Implementation: Rust, Implementation: Elixir
