### ISSUE TITLE
Key Exchange in NIF

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#413] opened 2020-09-10 06:04 UTC

**Comment by mrinalwadhwa** [comment] 2020-09-10 06:43
@SanjoDeundiak the goal is to make it possible to replace these functions with Rust equivalents
https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/lib/ockam/channel/xx.ex#L116-L212

**Comment by mrinalwadhwa** [comment] 2020-09-10 06:43
There is a possibility that a call like encode_message_2 is too long to be a NIF ... the concurrency strengths of Erlang VM come from being able to easily schedule thousands of concurrent processes. A long running NIF can totally kill that .... so we;ll have to measure once we have the above in place.

If this works, that would be win because then we won't have to maintain an elixir version of the key exchange.

**Comment by mrinalwadhwa** [comment] 2020-09-10 06:45
To start let's set this up in the ockam_vault_software mix project itself.  We can move to a different project later
https://github.com/ockam-network/ockam/tree/develop/implementations/e/applications/ockam_vault_software

**Comment by SanjoDeundiak** [comment] 2020-09-10 09:52
> There is a possibility that a call like encode_message_2 is too long to be a NIF ... the concurrency strengths of Erlang VM come from being able to easily schedule thousands of concurrent processes. A long running NIF can totally kill that .... so we;ll have to measure once we have the above in place.
> 
> If this works, that would be win because then we won't have to maintain an elixir version of the key exchange.

Encode message should be much faster than network request, db read/write, etc. So, if those things don't harm Erlang concurrency, how encode message would?

**Comment by mrinalwadhwa** [comment] 2020-09-10 18:09
The answer to that requires a deep dive into how the Erlang VM does scheduling of millions of processes.
Here's an old talk that delves into that https://www.youtube.com/watch?v=tBAM_N9qPno

In short, long running native functions are problematic.
Here's the warning form the docs, which provides a heuristic

> a well-behaving native function is to return to its caller within 1 millisecond

http://erlang.org/doc/man/erl_nif.html#WARNING
http://erlang.org/doc/man/erl_nif.html#lengthy_work

**Comment by lessless** [comment] 2020-10-02 06:35
Here is a short overview of the challenges from the tranches https://www.youtube.com/watch?v=xmUfTl33-fU#t=32m27s in just 3 minutes :)

**Comment by SanjoDeundiak** [comment] 2021-09-09 13:42
Duplicate of #676

**Closed by SanjoDeundiak** 2021-09-09 13:42 UTC
Labels: Implementation: Rust, Implementation: Elixir
